---
- name: nextcloud | check for app updates
  ansible.builtin.command:
    docker exec --user www-data nextcloud php occ app:update --showonly
  register: nextcloud_app_updates
  changed_when: false
  ignore_errors: true

- name: nextcloud | debug
  ansible.builtin.debug:
    var: nextcloud_app_updates.stdout_lines
  when:
    - not nextcloud_app_updates.failed

- name: nextcloud | apply app updates  # noqa: no-changed-when
  ansible.builtin.command:
    docker exec --user www-data nextcloud php occ app:update --all
  when:
    - not nextcloud_app_updates.failed
    - nextcloud_app_updates.stdout_lines | length > 0
